FROM docker.io/library/golang:1.22 AS builder
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/app ./cmd/app

FROM docker.io/library/alpine:3.20
WORKDIR /app
COPY --from=builder /out/app /app/app
COPY configs /app/configs
ENTRYPOINT ["/app/app", "-config", "/app/configs/pre/config.yaml"]
