-- ============================================================
-- accel_metric_scoring — 健康度指标规则表（1:1 对应 Excel）
-- 数据来源：scripts/⭐️健康度评估使用指标 (2).xlsx（新版，24 列；一票否决已补全）
--
-- 设计目标：
--   把 Excel 的列拆成规范化的独立列，评分时直接用列值匹配指标范围，
--   与旧的 accel_metrics / accel_metric_rules（JSON 存规则）独立并存。
--
-- 列 → Excel 表头映射：
--   seq_no              ← 序号
--   official_no         ← 官方编号
--   card_type           ← 卡的类型（GPU / NPU）
--   owner_subject       ← 归属主体（如 A单卡自身）
--   owner_subject_code  ← 归属主体映射码（见 字段映射.pdf）【新增】
--   metric_name         ← 字段名称
--   value_type          ← 指标数值类型
--   value_type_code     ← 指标数值类型映射码【新增】
--   health_purpose      ← 健康度用途（核心/归因/配置合规/性能容量）
--   health_purpose_code ← 健康度用途映射码【新增】
--   concept             ← 指标概念
--   dimension           ← 指标维度（暂不做数字映射）
--   unit                ← 单位
--   work_range          ← 工作范围
--   alert_upper         ← 告警上界（DOUBLE）【新增】
--   upper_bound         ← 指标上界（DOUBLE）
--   lower_bound         ← 指标下界（DOUBLE）
--   alert_lower         ← 告警下界（DOUBLE）【新增】
--   normal_rate         ← 正常速率
--   alert_rate          ← 告警速率【新增】
--   rate_unit           ← 速率单位（直接取 Excel 列，原 normal_rate_unit 改名）
--   bool_normal         ← 布尔正常
--   bool_abnormal       ← 布尔异常
--   enum_result         ← 枚举结果
--   is_veto             ← 关键判决（一票否决），1=是 0=否【新增】
--   derate_threshold    ← 降频/关机阈值
--   source_ref          ← 来源依据
--
-- 字段映射（见 字段映射.pdf）：
--   owner_subject_code:  A单卡自身=1 B链路（Host-Device&P2P）=2 C共享基础设施=3
--                        D环境与配置=4 E跨节点网络=5 空=6
--   value_type_code:     Gauge连续数值=1 Gauge_Rate比率=2 Counter累计计数=3
--                        Counter_Duration累计时长=4 Level_Count水位计数=5 Bool布尔=6
--                        Ordinal枚举=7 Other其他=8
--   health_purpose_code: 核心=1 归因=2 配置合规=3 性能容量=4
--   is_veto:             是=1 否=0
--   dimension:           暂不做数字映射（PDF 说明后续再定）
--
-- 执行方式（务必用 SET NAMES + SOURCE，否则中文乱码）：
--   docker cp "scripts/accel_metric_scoring.sql" mysql-standalone:/tmp/
--   docker exec mysql-standalone mysql -uroot -proot123 \
--     -e "SET NAMES utf8mb4; SOURCE /tmp/accel_metric_scoring.sql;" gpu_health
-- ============================================================

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `accel_metric_scoring`;

CREATE TABLE `accel_metric_scoring` (
    `id`                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '技术主键',
    `seq_no`              INT             NULL COMMENT '序号（Excel 内序号）',
    `official_no`         VARCHAR(191)    NULL COMMENT '官方编号，如 DCGM_FI_DEV_GPU_TEMP (150)',
    `card_type`           VARCHAR(64)     NULL COMMENT '卡的类型：GPU / NPU',
    `owner_subject_code`  TINYINT         NULL COMMENT '归属主体映射码：1=A单卡自身 2=B链路 3=C共享基础设施 4=D环境与配置 5=E跨节点网络 6=空',
    `metric_name`         VARCHAR(191)    NOT NULL COMMENT '字段名称（指标唯一标识）',
    `value_type_code`     TINYINT         NULL COMMENT '指标数值类型映射码：1~8（见字段映射.pdf）',
    `health_purpose_code` TINYINT         NULL COMMENT '健康度用途映射码：1=核心 2=归因 3=配置合规 4=性能容量',
    `concept`             TEXT            NULL COMMENT '指标概念',
    `dimension`           VARCHAR(64)     NULL COMMENT '指标维度，如 thermal温度散热',
    `unit`                VARCHAR(32)     NULL COMMENT '单位',
    `work_range`          VARCHAR(128)    NULL COMMENT '工作范围，如 0~85',
    `alert_upper`         DOUBLE          NULL COMMENT '告警上界（数值；非数值置 NULL）',
    `upper_bound`         DOUBLE          NULL COMMENT '指标上界（数值；非数值置 NULL）',
    `lower_bound`         DOUBLE          NULL COMMENT '指标下界（数值；非数值置 NULL）',
    `alert_lower`         DOUBLE          NULL COMMENT '告警下界（数值；非数值置 NULL）',
    `normal_rate`         DOUBLE          NULL COMMENT '正常速率（数值；非数值置 NULL）',
    `alert_rate`          DOUBLE          NULL COMMENT '告警速率（数值；非数值置 NULL）',
    `rate_unit`           VARCHAR(32)     NULL COMMENT '速率单位（直接取 Excel 速率单位列，如 μs/s、次/天）',
    `bool_normal`         TEXT            NULL COMMENT '布尔正常（布尔正常值）',
    `bool_abnormal`       TEXT            NULL COMMENT '布尔异常（布尔异常值）',
    `enum_result`         TEXT            NULL COMMENT '枚举结果（枚举类指标的取值含义）',
    `is_veto`             TINYINT         NULL COMMENT '关键判决（一票否决）：1=是 0=否',
    `derate_threshold`    TEXT            NULL COMMENT '降频/关机阈值（关键分档阈值）',
    `source_ref`          TEXT            NULL COMMENT '来源依据（出处）',
    `vendor`              VARCHAR(32)     NULL COMMENT '厂商：NVIDIA / 华为昇腾',
    `enum_score`          JSON            NULL COMMENT '枚举/位掩码评分规则（见 scoring/curve.go）',
    `remark`              VARCHAR(255)    NULL COMMENT '备注',
    `is_health_key`       TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否参与健康评分：1参与 0不参与',
    `created_at`          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_metric_name` (`metric_name`),
    KEY `idx_vendor` (`vendor`),
    KEY `idx_dimension` (`dimension`),
    KEY `idx_owner_code` (`owner_subject_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='健康度指标规则表';

-- 数据行由 scripts/gen_scoring_seed.py 从 Excel 自动生成，见下方 INSERT。

INSERT INTO `accel_metric_scoring`
(`seq_no`,`official_no`,`card_type`,`owner_subject_code`,`metric_name`,`value_type_code`,`health_purpose_code`,`concept`,`dimension`,`unit`,`work_range`,`alert_upper`,`upper_bound`,`lower_bound`,`alert_lower`,`normal_rate`,`alert_rate`,`rate_unit`,`bool_normal`,`bool_abnormal`,`enum_result`,`is_veto`,`derate_threshold`,`source_ref`,`vendor`) VALUES
(1,'DCGM_FI_DEV_GPU_TEMP (150)','GPU',1,'DCGM_FI_DEV_GPU_TEMP',1,1,'GPU 核心 (die) 当前温度，温度类主指标','thermal温度散热','℃','20~85',92,85,20,0,NULL,NULL,NULL,NULL,NULL,NULL,1,'降频(软件)=85；降频(硬件)=89；保护关机=92','【实测值】A100-SXM4 / H100-SXM5 nvidia-smi -q -d TEMPERATURE。H100 的 Max Op 为 87，取 85 作统一保守基线','NVIDIA'),
(2,'DCGM_FI_DEV_MEMORY_TEMP (140)','GPU',1,'DCGM_FI_DEV_MEMORY_TEMP',1,1,'HBM 显存颗粒温度','thermal温度散热','℃','20~95',NULL,95,20,0,NULL,NULL,NULL,NULL,NULL,NULL,1,'降频(软件热)=95，显存温度超此值触发 SW_THERMAL (0x20)','【实测值】A100/H100 HBM2e Memory Max Operating Temp = 95℃','NVIDIA'),
(3,'DCGM_FI_DEV_GPU_MAX_OP_TEMP (152)','GPU',1,'DCGM_FI_DEV_GPU_MAX_OP_TEMP',1,2,'GPU 最高工作温度，软件降频触发门限（设备常量）','thermal温度散热','℃','85~85',85,85,85,85,NULL,NULL,NULL,NULL,NULL,NULL,0,'★软件降频起始点 = 85','【实测值】A100-SXM4 = 85。程序优先读本字段实时值，读取失败回退 85','NVIDIA'),
(4,'DCGM_FI_DEV_SLOWDOWN_TEMP (158)','GPU',1,'DCGM_FI_DEV_SLOWDOWN_TEMP',1,2,'硬件降频温度门限，触发后核心时钟降至 1/2 或更低','thermal温度散热','℃','89~89',89,89,89,89,NULL,NULL,NULL,NULL,NULL,NULL,0,'★硬件降频门限 = 89','【实测值】A100-SXM4 / H100-SXM5 均为 89。读取失败回退 89','NVIDIA'),
(5,'DCGM_FI_DEV_SHUTDOWN_TEMP (159)','GPU',1,'DCGM_FI_DEV_SHUTDOWN_TEMP',1,2,'硬件保护关机温度门限，达到后 GPU 断电避免物理损伤','thermal温度散热','℃','92~92',92,92,92,92,NULL,NULL,NULL,NULL,NULL,NULL,1,'★保护关机门限 = 92','【实测值】A100-SXM4 / H100-SXM5 均为 92。读取失败回退 92','NVIDIA'),
(6,'DCGM_FI_DEV_THERMAL_VIOLATION (241)','GPU',1,'DCGM_FI_DEV_THERMAL_VIOLATION',4,1,'因温度触发降频的累计时长（自驱动加载起单调递增）','thermal温度散热','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'单位：μs/s，采样窗口增量 >0 即判定发生热降频。本字段即“已发生热降频”的直接证据，无需另设阈值','【官方规格】DCGM Field IDs','NVIDIA'),
(7,'DCGM_FI_DEV_FAN_SPEED (191)','GPU',1,'DCGM_FI_DEV_FAN_SPEED',2,2,'风扇转速占最大转速百分比（SXM 模组由整机散热，通常不上报）','thermal温度散热','%','0~90',95,90,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'持续 >90% 超过 10 分钟判定散热能力见底
转速 100% 且温度仍 >85 → 散热系统已失效','【行业经验】90% 为持续运行告警线','NVIDIA'),
(8,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_CURRENT (858)','GPU',3,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_CURRENT',1,1,'NVSwitch 芯片当前温度','thermal温度散热','℃','20~90',100,90,20,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'降频=90；关机=100','【行业经验】NVIDIA 未公开 NVSwitch 门限，按 DGX 整机运维经验取 90/100，程序优先读字段 859/860','NVIDIA'),
(9,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SLOWDOWN (859)','GPU',3,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SLOWDOWN',1,2,'NVSwitch 降频温度门限','thermal温度散热','℃','90~90',90,90,90,90,NULL,NULL,NULL,NULL,NULL,NULL,0,'★NVSwitch 降频门限 = 90','【行业经验】读取失败回退 90','NVIDIA'),
(10,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SHUTDOWN (860)','GPU',3,'DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SHUTDOWN',1,2,'NVSwitch 关机温度门限','thermal温度散热','℃','100~100',100,100,100,100,NULL,NULL,NULL,NULL,NULL,NULL,0,'★NVSwitch 关机门限 = 100','【行业经验】读取失败回退 100','NVIDIA'),
(11,'DCGM_FI_DEV_POWER_USAGE (155)','GPU',1,'DCGM_FI_DEV_POWER_USAGE',1,2,'整卡实时功耗','power功耗电源','W','20~400',400,400,20,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'★功耗达到 400 触发软件功率封顶 SW_POWER_CAP (0x4)。H100-SXM5 对应值为 700','【官方规格】A100-SXM4-80GB TDP=400W；H100-SXM5=700W；A100-PCIe=300W。空闲 50~80W 为实测值','NVIDIA'),
(12,'DCGM_FI_DEV_ENFORCED_POWER_LIMIT (164)','GPU',1,'DCGM_FI_DEV_ENFORCED_POWER_LIMIT',1,2,'驱动综合所有限制因素后实际强制执行的功率上限','power功耗电源','W','400~400',400,400,400,400,NULL,NULL,NULL,NULL,NULL,NULL,0,'★功率封顶点，实时功耗触及此值即降频','【实测值】A100-SXM4-80GB = 400。读取失败回退 400','NVIDIA'),
(13,'DCGM_FI_DEV_POWER_MGMT_LIMIT (160)','GPU',1,'DCGM_FI_DEV_POWER_MGMT_LIMIT',1,3,'当前生效的功率管理上限（可由运维用 nvidia-smi-pl修改）','power功耗电源','W','100~400',400,400,100,100,NULL,NULL,NULL,NULL,NULL,NULL,0,'下调到 <400 会提前触发功率降频，应单独识别为配置类异常而非硬件故障','【实测值】A100-SXM4-80GB 可设区间 100~400','NVIDIA'),
(14,'DCGM_FI_DEV_POWER_MGMT_LIMIT_MIN (161)','GPU',1,'DCGM_FI_DEV_POWER_MGMT_LIMIT_MIN',1,3,'功率管理上限可设置的最小值','power功耗电源','W','100~100',100,100,100,100,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【实测值】A100-SXM4-80GB = 100W','NVIDIA'),
(15,'DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX (162)','GPU',1,'DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX',1,3,'功率管理上限可设置的最大值','power功耗电源','W','400~400',400,400,400,400,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【实测值】A100-SXM4-80GB = 400W；H100-SXM5 = 700W','NVIDIA'),
(16,'DCGM_FI_DEV_POWER_MGMT_LIMIT_DEF (163)','GPU',1,'DCGM_FI_DEV_POWER_MGMT_LIMIT_DEF',1,3,'出厂默认功率管理上限（TDP 基准）','power功耗电源','W','400~400',400,400,400,400,NULL,NULL,NULL,NULL,NULL,NULL,0,'用于判断当前功率上限是否被人为下调','【实测值】A100-SXM4-80GB = 400W','NVIDIA'),
(17,'DCGM_FI_DEV_POWER_VIOLATION (240)','GPU',1,'DCGM_FI_DEV_POWER_VIOLATION',4,1,'因功耗超限触发降频的累计时长','power功耗电源','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'单位μs/s，采样窗口增量 >0 即判定发生功率降频。本字段即“已发生功率降频”的直接证据','【官方规格】DCGM Field IDs','NVIDIA'),
(18,'DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION (156)','GPU',1,'DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION',3,4,'自驱动最近一次加载以来的累计能耗（重装/重载驱动后归零）','power功耗电源','mJ','单调递增',NULL,NULL,0,NULL,400000,400000,NULL,NULL,NULL,NULL,0,'速率上界 400000 mJ/s（=400W）；速率应等于字段155×1000，偏差 >10% 说明采样异常','【官方规格】DCGM Field IDs；上界由 TDP 400W 换算','NVIDIA'),
(19,'DCGM_FI_DEV_CLOCK_THROTTLE_REASONS (112)','GPU',1,'DCGM_FI_DEV_CLOCK_THROTTLE_REASONS',7,1,'当前降频原因位掩码，判定“是否降频+为何降频”的唯一权威字段','power功耗电源','bitmask','0x0 / 0x1 / 0x2 属正常',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0x0 无降频；0x1 GPU_IDLE 空闲降频；0x2 CLOCKS_SETTING 人为设定应用时钟；0x4 SW_POWER_CAP 软件功率封顶；0x8 HW_SLOWDOWN 硬件降频；0x10 SYNC_BOOST；0x20 SW_THERMAL 软件热降频；0x40 HW_THERMAL 硬件热降频；0x80 HW_POWER_BRAKE 外部电源刹车；0x100 DISPLAY_CLOCKS',0,'★判定式：(value & 0xFC) != 0 即存在异常降频。0x8/0x40/0x80 高危，0x4/0x20 中危','【官方规格】DCGM Field Constants (dcgm_fields.h)','NVIDIA'),
(20,'DCGM_FI_DEV_PSTATE (190)','GPU',1,'DCGM_FI_DEV_PSTATE',7,2,'性能状态 P-State，0 为最高性能档','power功耗电源','档位','0~0（有负载时）',NULL,15,0,NULL,NULL,NULL,NULL,NULL,NULL,'0 (P0)；有持续负载但值 >0',0,'空闲时 P-State 升高属节能行为，判定前先确认 GPU_UTIL >10%','【官方规格】DCGM Field IDs','NVIDIA'),
(21,'DCGM_FI_DEV_BOARD_LIMIT_VIOLATION (243)','GPU',1,'DCGM_FI_DEV_BOARD_LIMIT_VIOLATION',4,1,'因板级供电/电流限制触发降频的累计时长','power功耗电源','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,1,'增量 >0 表示板级供电不足导致降频，需排查整机电源','【官方规格】DCGM Field IDs','NVIDIA'),
(22,'DCGM_FI_DEV_FB_TOTAL (250)','GPU',1,'DCGM_FI_DEV_FB_TOTAL',1,1,'帧缓存(显存)总量','memory显存可靠性','MB','81920~81920',81920,81920,81920,81920,NULL,NULL,NULL,NULL,NULL,NULL,0,'低于标称说明显存颗粒被屏蔽，属永久性降级。A100-40GB=40960，H100-80GB=81559','【实测值】A100-SXM4-80GB = 81920 MB','NVIDIA'),
(23,'DCGM_FI_DEV_FB_USED (252)','GPU',1,'DCGM_FI_DEV_FB_USED',1,4,'已使用显存','memory显存可靠性','MB','0~77824',81920,77824,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'77824 = 总量 95%，作为显存耗尽告警线','【行业经验】95% 为通行告警水位','NVIDIA'),
(24,'DCGM_FI_DEV_FB_FREE (251)','GPU',1,'DCGM_FI_DEV_FB_FREE',1,4,'空闲显存','memory显存可靠性','MB','4096~81920',81920,81920,4096,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'低于 4096 MB 判定显存紧张','【行业经验】4 GB 余量为通行告警线','NVIDIA'),
(25,'DCGM_FI_DEV_FB_RESERVED (253)','GPU',1,'DCGM_FI_DEV_FB_RESERVED',1,1,'驱动保留显存（含 ECC 开销、退役页与重映射行占用）','memory显存可靠性','MB','0~2048',NULL,2048,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'A100-80GB 开 ECC 时正常保留 800~1200 MB，超过 2048 说明退役页/重映射行显著增加','【实测值】正常保留 800~1200 MB；【行业经验】2048 为告警线','NVIDIA'),
(26,'DCGM_FI_DEV_FB_USED_PERCENT (254)','GPU',1,'DCGM_FI_DEV_FB_USED_PERCENT',2,4,'显存使用率 = Used/(Total-Reserved)','memory显存可靠性','比例(0~1)','0~0.95',1,0.95,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'0.95 为告警线','【官方规格】取值域 0.0~1.0；【行业经验】0.95 告警','NVIDIA'),
(27,'DCGM_FI_DEV_ECC_CURRENT (300)','GPU',1,'DCGM_FI_DEV_ECC_CURRENT',6,3,'当前生效的 ECC 模式','memory显存可靠性',NULL,'恒为 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,0,'1 = Enabled；0 = Disabled（失去纠错能力，生产环境禁止）','【官方规格】DCGM Field IDs','NVIDIA'),
(28,'DCGM_FI_DEV_ECC_PENDING (301)','GPU',1,'DCGM_FI_DEV_ECC_PENDING',6,3,'下次重启后生效的 ECC 模式','memory显存可靠性',NULL,'恒为 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,0,'1，且等于字段300；!= 字段300（存在待重启生效的 ECC 模式变更）','【官方规格】DCGM Field IDs','NVIDIA'),
(29,'DCGM_FI_DEV_ECC_SBE_VOL_TOTAL (310)','GPU',1,'DCGM_FI_DEV_ECC_SBE_VOL_TOTAL',5,1,'易失(volatile)单比特可纠正 ECC 错误总数，驱动重载/GPU 复位后清零','memory显存可靠性','次','0~24',NULL,24,0,NULL,24,24,'次/天',NULL,NULL,NULL,0,'应≤1次/小时；>24 次/天 判定 HBM 开始退化；>100 次/天 判定需停机检修','【行业经验】1 次/小时为关注线，24 次/天为告警线','NVIDIA'),
(30,'DCGM_FI_DEV_ECC_DBE_VOL_TOTAL (311)','GPU',1,'DCGM_FI_DEV_ECC_DBE_VOL_TOTAL',5,1,'易失双比特不可纠正 ECC 错误总数，通常直接导致任务崩溃','memory显存可靠性','次','0~0',NULL,0,0,NULL,0,0,'次/天','0','>0（任意一次即严重故障，立即隔离该卡）',NULL,1,'次/天；触发 DCGM_FR_DBE_VIOLATION','【官方规格】DCGM dcgm_errors.h','NVIDIA'),
(31,'DCGM_FI_DEV_ECC_SBE_AGG_TOTAL (312)','GPU',1,'DCGM_FI_DEV_ECC_SBE_AGG_TOTAL',3,1,'持久化(aggregate)单比特 ECC 错误总数，跨重启保留','memory显存可靠性','次','0~1000',NULL,1000,0,NULL,0,24,'次',NULL,NULL,NULL,0,'≤24 次/天；累计 >1000 次建议安排 RMA 评估','【行业经验】1000 次累计为业内常用 RMA 评估参考线','NVIDIA'),
(32,'DCGM_FI_DEV_ECC_DBE_AGG_TOTAL (313)','GPU',1,'DCGM_FI_DEV_ECC_DBE_AGG_TOTAL',3,1,'持久化双比特 ECC 错误总数，跨重启保留','memory显存可靠性','次','0~0',NULL,0,0,NULL,0,0,'次',NULL,NULL,NULL,1,'次/天，>0（历史存在不可纠正错误，RMA 候选）','【官方规格】DCGM Field IDs；【行业经验】任意 >0 即 RMA 候选','NVIDIA'),
(33,'DCGM_FI_DEV_ECC_DBE_VOL_DEV (319)','GPU',1,'DCGM_FI_DEV_ECC_DBE_VOL_DEV',5,1,'显存颗粒(device memory)双比特 ECC 错误，用于定位错误发生位置','memory显存可靠性','次','0~0',NULL,0,0,NULL,0,0,'次/天','0','>0',NULL,1,'页/天','【官方规格】DCGM Field IDs','NVIDIA'),
(34,'DCGM_FI_DEV_RETIRED_SBE (390)','GPU',1,'DCGM_FI_DEV_RETIRED_SBE',3,1,'因单比特错误而退役的显存页数（Volta 及更早架构机制）','memory显存可靠性','页','0~0',60,0,0,NULL,0,1,'页/天',NULL,NULL,NULL,0,'页/天，新增即需关注
SBE+DBE 退役页合计达 64 页（页黑名单上限）即需 RMA，60 为预警线','【行业经验】64 页为 NVIDIA 页黑名单容量，业内通行 RMA 判据','NVIDIA'),
(35,'DCGM_FI_DEV_RETIRED_DBE (391)','GPU',1,'DCGM_FI_DEV_RETIRED_DBE',3,1,'因双比特错误而退役的显存页数','memory显存可靠性','页','0~0',1,0,0,NULL,0,1,'页/天',NULL,NULL,NULL,1,'页/天，与 SBE 退役页合计上限 64 页，>0异常','【行业经验】同上','NVIDIA'),
(36,'DCGM_FI_DEV_RETIRED_PENDING (392)','GPU',1,'DCGM_FI_DEV_RETIRED_PENDING',5,1,'待退役页数，需 GPU 复位后才实际生效','memory显存可靠性','页','0~0',NULL,0,0,NULL,0,0,'页/天','0','>0（存在待处理坏页，需安排 GPU reset）',NULL,1,'页/天','【官方规格】DCGM Field IDs / DCGM Diagnostics','NVIDIA'),
(37,'DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS (393)','GPU',1,'DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS',3,1,'因不可纠正错误发生行重映射的行数（Ampere 及以后架构）','memory显存可靠性','行','0~0',NULL,0,0,NULL,0,0,'行',NULL,NULL,NULL,1,'行/天，>0（HBM 存在硬缺陷，RMA 候选）','【行业经验】不可纠正重映射任意 >0 即 RMA 判据','NVIDIA'),
(38,'DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS (394)','GPU',1,'DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS',3,1,'因可纠正错误发生行重映射的行数','memory显存可靠性','行','0~0',8,0,0,NULL,0,8,'行/天',NULL,NULL,NULL,0,'行/天；累计 >8 行进入关注，>60 行建议 RMA每 bank 备用行有限，60 行为预警线','【行业经验】8 行关注 / 60 行 RMA 为业内通行梯度','NVIDIA'),
(39,'DCGM_FI_DEV_ROW_REMAP_FAILURE (395)','GPU',1,'DCGM_FI_DEV_ROW_REMAP_FAILURE',6,1,'行重映射是否失败（备用行耗尽）','memory显存可靠性',NULL,'恒为 0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,1,'0 = 未失败；1 = 重映射失败，显存已无冗余，立即隔离并 RMA','【官方规格】DCGM Field IDs','NVIDIA'),
(40,'DCGM_FI_DEV_ROW_REMAP_PENDING (396)','GPU',1,'DCGM_FI_DEV_ROW_REMAP_PENDING',6,1,'是否存在待生效的行重映射（需 GPU 复位）','memory显存可靠性',NULL,'恒为 0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,0,'0 = 无待处理项；1 = 有待生效重映射，需 GPU reset 后方恢复满配可靠性','【官方规格】DCGM Field IDs','NVIDIA'),
(41,'DCGM_FI_DEV_BAR1_TOTAL (90)','GPU',1,'DCGM_FI_DEV_BAR1_TOTAL',1,2,'BAR1 地址空间总量','memory显存可靠性','MB','65536~65536',65536,65536,65536,65536,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【实测值】A100-SXM4-80GB = 65536 MB','NVIDIA'),
(42,'DCGM_FI_DEV_BAR1_USED (92)','GPU',1,'DCGM_FI_DEV_BAR1_USED',1,2,'BAR1 已用量，耗尽会导致 P2P / GPUDirect RDMA 失败','memory显存可靠性','MB','0~58982',65536,58982,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'58982 = 总量 90%，超过即预警 P2P 可能失败','【行业经验】90% 为通行告警水位','NVIDIA'),
(43,'DCGM_FI_DEV_MEM_COPY_UTIL (204)','GPU',1,'DCGM_FI_DEV_MEM_COPY_UTIL',2,4,'显存读写(拷贝)通道时间占比','memory显存可靠性','%','0~100',100,90,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'持续 >90% 且 SM_ACTIVE <0.3 说明访存瓶颈（性能问题，非硬件故障）','【官方规格】DCGM Field IDs','NVIDIA'),
(44,'DCGM_FI_DEV_PCIE_REPLAY_COUNTER (202)','GPU',2,'DCGM_FI_DEV_PCIE_REPLAY_COUNTER',3,1,'PCIe 链路层重传次数，反映链路信号质量','pcie总线','次','长期不增长',NULL,NULL,0,NULL,0,8,'次/分钟',NULL,NULL,NULL,0,'★≤8 次/分钟；>8 次/分钟 触发 DCGM 健康检查 Warning；>100 次/分钟 判定链路严重劣化','【官方规格】NVIDIA DCGM User Guide：Detected more than 8 PCIe replays per minute','NVIDIA'),
(45,'DCGM_FI_DEV_PCIE_MAX_LINK_GEN (235)','GPU',2,'DCGM_FI_DEV_PCIE_MAX_LINK_GEN',7,2,'PCIe 最大支持代数（设备能力）','pcie总线','代','4~4',NULL,4,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'A100 = Gen4；H100 = Gen5（值为 5）','【官方规格】A100 支持 PCIe 4.0','NVIDIA'),
(46,'DCGM_FI_DEV_PCIE_LINK_GEN (237)','GPU',2,'DCGM_FI_DEV_PCIE_LINK_GEN',7,1,'PCIe 当前协商代数','pcie总线','代','4~4',NULL,4,4,NULL,NULL,NULL,NULL,NULL,NULL,'4（等于字段235）；< 4（链路降代，带宽按比例损失）',0,'Gen4→Gen3 带宽腰斩，Gen4→Gen1 仅剩 1/8','【官方规格】判据为 字段237 == 字段235','NVIDIA'),
(47,'DCGM_FI_DEV_PCIE_MAX_LINK_WIDTH (236)','GPU',2,'DCGM_FI_DEV_PCIE_MAX_LINK_WIDTH',7,2,'PCIe 最大链路宽度（设备能力）','pcie总线','lane','16~16',NULL,16,16,NULL,NULL,NULL,NULL,NULL,NULL,'数据中心训练卡均为 x16',0,NULL,'【官方规格】数据中心训练卡均为 x16','NVIDIA'),
(48,'DCGM_FI_DEV_PCIE_LINK_WIDTH (238)','GPU',2,'DCGM_FI_DEV_PCIE_LINK_WIDTH',7,1,'PCIe 当前协商链路宽度','pcie总线','lane','16~16',NULL,16,16,NULL,NULL,NULL,NULL,NULL,NULL,'16（等于字段236）、< 16（降宽至 x8/x4/x1）',0,'降宽通常源于插槽接触不良、金手指氧化或 BIOS 配置错误','【官方规格】判据为 字段238 == 字段236','NVIDIA'),
(49,'DCGM_FI_PROF_PCIE_TX_BYTES (1009)','GPU',2,'DCGM_FI_PROF_PCIE_TX_BYTES',3,4,'PCIe 发送字节数（含包头与载荷，GPU→Host 方向）','pcie总线','Byte','0~31500000000',NULL,31500000000,0,NULL,31.5,20,'GB/s',NULL,NULL,NULL,0,'速率上界 31.5 GB/s（Gen4 x16 单向理论值），实测有效带宽通常 24~26 GB/s。
满载时速率长期 <20 GB/s 需排查链路降级','【官方规格】PCIe 4.0 x16 = 16 GT/s × 16 lane × 128/130 ÷ 8 = 31.5 GB/s','NVIDIA'),
(50,'DCGM_FI_PROF_PCIE_RX_BYTES (1010)','GPU',2,'DCGM_FI_PROF_PCIE_RX_BYTES',3,4,'PCIe 接收字节数（Host→GPU 方向）','pcie总线','Byte','0~31500000000',NULL,31500000000,0,NULL,31.5,20,'GB/s',NULL,NULL,NULL,0,'速率上界 31.5 GB/s，实测有效 24~26 GB/s','【官方规格】同上','NVIDIA'),
(51,'DCGM_FI_DEV_PCIE_TX_THROUGHPUT (200)','GPU',2,'DCGM_FI_DEV_PCIE_TX_THROUGHPUT',8,4,'PCIe 发送吞吐（官方标注 Deprecated，新项目改用字段1009）','pcie总线','KB/s','0~30761718',NULL,30761718,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'30761718 KB/s = 31.5 GB/s','【官方规格】DCGM Field IDs 标注 Deprecated','NVIDIA'),
(52,'DCGM_FI_DEV_PCIE_RX_THROUGHPUT (201)','GPU',2,'DCGM_FI_DEV_PCIE_RX_THROUGHPUT',8,4,'PCIe 接收吞吐（官方标注 Deprecated，新项目改用字段1010）','pcie总线','KB/s','0~30761718',NULL,30761718,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【官方规格】DCGM Field IDs 标注 Deprecated','NVIDIA'),
(53,'DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL (409)','GPU',2,'DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL',3,1,'NVLink FLIT(流控单元) CRC 错误总数（全链路汇总）','nvlink片间互连（DCGM）','次','长期不增长',NULL,NULL,0,NULL,0,10,'次/分钟',NULL,NULL,NULL,0,'★<100 次/秒（DCGM 官方阈值）；工程建议收紧到 <10 次/分钟','【官方规格】DCGM dcgm_errors.h：DCGM_FR_NVLINK_CRC_ERROR_THRESHOLD = 100 次/秒','NVIDIA'),
(54,'DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL (419)','GPU',2,'DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL',3,1,'NVLink 数据 CRC 错误总数','nvlink片间互连（DCGM）','次','长期不增长',NULL,NULL,0,NULL,0,10,'次/分钟',NULL,NULL,NULL,0,'★<100 次/秒；工程建议 <10 次/分钟','【官方规格】DCGM dcgm_errors.h','NVIDIA'),
(55,'DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL (429)','GPU',2,'DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL',3,1,'NVLink 链路重传次数总数','nvlink片间互连（DCGM）','次','恒不增长',NULL,NULL,0,NULL,0,10,'次/分钟',NULL,NULL,NULL,0,'0 次/分钟；>10 次/分钟 判定链路劣化','【行业经验】10 次/分钟为通行告警线','NVIDIA'),
(56,'DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL (439)','GPU',2,'DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL',3,1,'NVLink 链路恢复(重训练)次数总数','nvlink片间互连（DCGM）','次','恒不增长',NULL,NULL,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'次/小时；任意增量都表示链路曾中断重训，直接影响集合通信','【行业经验】任意 >0 即告警','NVIDIA'),
(57,'DCGM_FI_DEV_GPU_NVLINK_ERRORS (450)','GPU',2,'DCGM_FI_DEV_GPU_NVLINK_ERRORS',3,1,'GPU 侧 NVLink 错误汇总','nvlink片间互连（DCGM）','次','恒不增长',NULL,NULL,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'次/小时','【官方规格】DCGM Field IDs','NVIDIA'),
(58,'DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL (449)','GPU',2,'DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL',3,4,'NVLink 全链路累计传输量','nvlink片间互连（DCGM）','KB','0~600000000',NULL,600000000,0,NULL,600,NULL,'GB/s',NULL,NULL,NULL,0,'速率上界 600 GB/s（A100 NVLink3 双向聚合）；H100 NVLink4 为 900 GB/s','【官方规格】A100 12 条 NVLink3 × 50 GB/s = 600 GB/s 双向','NVIDIA'),
(59,'DCGM_FI_PROF_NVLINK_TX_BYTES (1011)','GPU',2,'DCGM_FI_PROF_NVLINK_TX_BYTES',3,4,'NVLink 发送字节数（含包头与载荷）','nvlink片间互连（DCGM）','Byte','0~300000000000',NULL,300000000000,0,NULL,300,NULL,'GB/s',NULL,NULL,NULL,0,'速率上界 300 GB/s（单向）','【官方规格】A100 单向 300 GB/s；H100 单向 450 GB/s','NVIDIA'),
(60,'DCGM_FI_PROF_NVLINK_RX_BYTES (1012)','GPU',2,'DCGM_FI_PROF_NVLINK_RX_BYTES',3,4,'NVLink 接收字节数','nvlink片间互连（DCGM）','Byte','0~300000000000',NULL,300000000000,0,NULL,300,NULL,'GB/s',NULL,NULL,NULL,0,'速率上界 300 GB/s（单向）','【官方规格】同上','NVIDIA'),
(61,'DCGM_FI_DEV_NVSWITCH_LINK_STATUS (870)','GPU',3,'DCGM_FI_DEV_NVSWITCH_LINK_STATUS',7,1,'NVSwitch 上 NVLink 端口状态','nvlink片间互连（DCGM）',NULL,'恒为 2',NULL,3,-1,NULL,NULL,NULL,NULL,NULL,NULL,'2 = ACTIVE；-1 UNKNOWN；0 OFF ；1 SAFE ；3 ERROR',0,NULL,'【官方规格】DCGM Field IDs','NVIDIA'),
(62,'DCGM_FI_DEV_NVSWITCH_LINK_FATAL_ERRORS (782)','GPU',3,'DCGM_FI_DEV_NVSWITCH_LINK_FATAL_ERRORS',3,1,'NVSwitch 端口致命错误计数（端口 0-17）','nvlink片间互连（DCGM）','次','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,1,'次/小时，>0（触发 DCGM_FR_NVSWITCH_FATAL_ERROR，业务需立即迁移）','【官方规格】DCGM dcgm_errors.h','NVIDIA'),
(63,'DCGM_FI_DEV_NVSWITCH_LINK_NON_FATAL_ERRORS (783)','GPU',3,'DCGM_FI_DEV_NVSWITCH_LINK_NON_FATAL_ERRORS',3,1,'NVSwitch 端口非致命错误计数','nvlink片间互连（DCGM）','次','0~10',NULL,10,0,NULL,0,10,'次',NULL,NULL,NULL,0,'次/小时；累计 >10 进入关注，>10（可继续承载业务但需监控）','【行业经验】非致命错误 10 次为关注线','NVIDIA'),
(64,'DCGM_FI_DEV_NVSWITCH_FATAL_ERRORS (856)','GPU',3,'DCGM_FI_DEV_NVSWITCH_FATAL_ERRORS',7,1,'NVSwitch 致命错误事件，字段值即具体 SXid 码','nvlink片间互连（DCGM）','SXid 码','无上报',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'无 SXid 上报；上报任意致命 SXid（触发 DCGM_FR_SXID_ERROR）',1,NULL,'【官方规格】DCGM dcgm_errors.h','NVIDIA'),
(65,'DCGM_FI_DEV_NVSWITCH_RESET_REQUIRED (864)','GPU',3,'DCGM_FI_DEV_NVSWITCH_RESET_REQUIRED',6,1,'NVSwitch 是否需要复位','nvlink片间互连（DCGM）',NULL,'恒为 0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,1,'0 = 无需复位；1 = 需要复位（整机 NVLink 域受影响）','【官方规格】DCGM Field IDs','NVIDIA'),
(66,'DCGM_FI_DEV_XID_ERRORS (230)','GPU',1,'DCGM_FI_DEV_XID_ERRORS',7,1,'驱动上报的 XID 错误码，GPU 稳定性的核心事件源','driver驱动（DCGM）','XID 码','无 XID 上报',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'无 XID 事件；13/31/43/45 属应用侧内存越界，不计入硬件健康度；硬件类高危 XID：48/63/64/94/95（ECC 与行重映射）；61/62/69/74（内部硬件与总线错误）；79（GPU 掉出总线）',1,'XID 79 等价于设备不可用，健康度直接判为故障（0 分）','【官方规格】DCGM Field IDs；dcgm_errors.h (DCGM_FR_XID_ERROR=101)','NVIDIA'),
(67,'DCGM_FI_DRIVER_VERSION (1)','GPU',4,'DCGM_FI_DRIVER_VERSION',8,3,'NVIDIA 驱动版本','driver驱动（DCGM）',NULL,'≥ 535.104.05',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'全集群一致且 ≥ 535.104.05（A100/H100 生产推荐 LTS 分支）','跨节点版本不一致，或低于 535 分支',NULL,0,'低版本驱动在 Hopper 上易触发偶发 XID，建议统一到 535 或 550 LTS','【行业经验】535 为 A100/H100 通行生产基线分支','NVIDIA'),
(68,'DCGM_FI_CUDA_DRIVER_VERSION (5)','GPU',4,'DCGM_FI_CUDA_DRIVER_VERSION',8,3,'CUDA 驱动版本','driver驱动（DCGM）',NULL,'≥ 12020',NULL,12080,12020,NULL,NULL,NULL,NULL,'≥ 12020（CUDA 12.2）且全集群一致','< 12020 或跨节点不一致',NULL,0,NULL,'【行业经验】CUDA 12.2 为当前主流训练框架的通行下限','NVIDIA'),
(69,'DCGM_FI_DEV_INFOROM_CONFIG_VALID (84)','GPU',4,'DCGM_FI_DEV_INFOROM_CONFIG_VALID',6,1,'从 Flash 读取 InfoROM 并校验 checksum 的结果','driver驱动（DCGM）',NULL,'恒为 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,1,'1 = 校验通过；0 = InfoROM 损坏（ECC 历史与配置丢失，DCGM 上报 InfoROM system Warning）','【官方规格】DCGM Field IDs；DCGM User Guide 健康检查示例','NVIDIA'),
(70,'DCGM_FI_DEV_PERSISTENCE_MODE (66)','GPU',4,'DCGM_FI_DEV_PERSISTENCE_MODE',6,3,'驱动持久化模式','driver驱动（DCGM）',NULL,'恒为 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,0,'1 = Enabled；0 = Disabled（首次调用有秒级延迟，且卡状态会复位）','【行业经验】生产集群必开','NVIDIA'),
(71,'DCGM_FI_DEV_MIG_MODE (67)','GPU',4,'DCGM_FI_DEV_MIG_MODE',6,3,'MIG 切分模式开关','driver驱动（DCGM）',NULL,'训练集群恒为 0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,0,'0（训练集群不切分）；1（与训练场景规划不符，会导致调度与监控口径错乱）。推理集群若规划启用 MIG，正常值反转为 1','【行业经验】大规模训练集群默认关闭 MIG','NVIDIA'),
(72,'DCGM_FI_DEV_CC_MODE (74)','GPU',4,'DCGM_FI_DEV_CC_MODE',6,3,'机密计算 / Ampere Protected Memory 状态','driver驱动（DCGM）',NULL,'恒为 0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,0,'0（常规训练集群不启用）；1（开启后性能有损失，需与安全策略核对）','【行业经验】常规训练集群默认关闭','NVIDIA'),
(73,'DCGM_FI_DEV_RELIABILITY_VIOLATION (245)','GPU',1,'DCGM_FI_DEV_RELIABILITY_VIOLATION',4,1,'因可靠性策略限制而降频的累计时长','driver驱动（DCGM）','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'增量 >0 表示驱动因可靠性原因主动限制性能','【官方规格】DCGM Field IDs','NVIDIA'),
(74,'DCGM_FI_DEV_COUNT (4)','GPU',4,'DCGM_FI_DEV_COUNT',1,1,'节点上被驱动识别到的 GPU 数量','driver驱动（DCGM）','个','8~8',8,8,8,8,NULL,NULL,NULL,NULL,NULL,NULL,1,'4 卡节点则基线改为 4','【行业经验】DGX/HGX 标准训练节点为 8 卡','NVIDIA'),
(75,'DCGM_FI_DEV_GPU_UTIL (203)','GPU',1,'DCGM_FI_DEV_GPU_UTIL',2,2,'GPU 忙碌时间占比（粗粒度，不反映算力饱和度）','compute算力性能','%','0~100',100,90,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'本字段 >90% 但 PROF_SM_ACTIVE <0.3 → 算力空转，按性能问题处理','【官方规格】DCGM Field IDs','NVIDIA'),
(76,'DCGM_FI_DEV_SM_CLOCK (100)','GPU',1,'DCGM_FI_DEV_SM_CLOCK',1,1,'SM 当前频率，判断是否降频的直接观测量','compute算力性能','MHz','1340~1410（满载时）',1410,1340,1340,1340,NULL,NULL,NULL,NULL,NULL,NULL,0,'★满载判据：SM_CLOCK < 1340（即 95% × 1410）且字段112 出现热/功率位 → 判定降频。H100-SXM5 基准为 1980','【实测值】A100-SXM4 最大 SM 频率 = 1410 MHz；【行业经验】95% 为降频判定线','NVIDIA'),
(77,'DCGM_FI_DEV_MAX_SM_CLOCK (113)','GPU',1,'DCGM_FI_DEV_MAX_SM_CLOCK',1,2,'设备支持的最大 SM 频率','compute算力性能','MHz','1410~1410',1410,1410,1410,1410,NULL,NULL,NULL,NULL,NULL,NULL,0,'作为 SM_CLOCK 的分母基准；H100-SXM5 = 1980','【实测值】A100-SXM4 = 1410 MHz','NVIDIA'),
(78,'DCGM_FI_DEV_MEM_CLOCK (101)','GPU',1,'DCGM_FI_DEV_MEM_CLOCK',1,2,'显存当前频率','compute算力性能','MHz','1154~1215（满载时）',1215,1215,1154,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'低于 1154（95% × 1215）判定显存降频','【实测值】A100-SXM4-80GB HBM2e = 1215 MHz','NVIDIA'),
(79,'DCGM_FI_DEV_MAX_MEM_CLOCK (114)','GPU',1,'DCGM_FI_DEV_MAX_MEM_CLOCK',1,2,'设备支持的最大显存频率','compute算力性能','MHz','1215~1215',1215,1215,1215,1215,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【实测值】A100-SXM4 = 1215 MHz；H100-SXM5 = 2619 MHz','NVIDIA'),
(80,'DCGM_FI_DEV_APP_SM_CLOCK (110)','GPU',1,'DCGM_FI_DEV_APP_SM_CLOCK',1,3,'应用锁定的 SM 时钟设定值','compute算力性能','MHz','1410~1410',1410,1410,1410,1410,NULL,NULL,NULL,NULL,NULL,NULL,0,'运维用 nvidia-smi -ac 锁频后此值会低于最大值，属配置类异常','【实测值】A100-SXM4 默认 = 1410 MHz','NVIDIA'),
(81,'DCGM_FI_DEV_APP_MEM_CLOCK (111)','GPU',1,'DCGM_FI_DEV_APP_MEM_CLOCK',1,3,'应用锁定的显存时钟设定值','compute算力性能','MHz','1215~1215',1215,1215,1215,1215,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【实测值】A100-SXM4-80GB = 1215 MHz','NVIDIA'),
(82,'DCGM_FI_PROF_GR_ENGINE_ACTIVE (1001)','GPU',1,'DCGM_FI_PROF_GR_ENGINE_ACTIVE',2,4,'图形/计算引擎处于活跃状态的时间占比','compute算力性能','比例(0~1)','0.5~1.0（训练稳定期）',1,1,0.5,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'训练期低于 0.5 提示存在数据供给或通信瓶颈','【行业经验】训练稳定期 0.5 为关注线','NVIDIA'),
(83,'DCGM_FI_PROF_SM_ACTIVE (1002)','GPU',1,'DCGM_FI_PROF_SM_ACTIVE',2,2,'至少有 1 个 warp 驻留的 SM 周期占比（真实算力占用）','compute算力性能','比例(0~1)','0.6~1.0（训练稳定期）',1,1,0.6,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'★慢卡判据：同集群同负载下，本值低于同批次中位数 10% 即判定慢卡','【行业经验】训练稳定期 0.6 为通行下限','NVIDIA'),
(84,'DCGM_FI_PROF_SM_OCCUPANCY (1003)','GPU',1,'DCGM_FI_PROF_SM_OCCUPANCY',2,4,'SM 上驻留 warp 数占理论最大值的比例','compute算力性能','比例(0~1)','0.3~1.0',1,1,0.3,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'占用率低主要反映 kernel 设计问题，不作为硬件健康度扣分项','【行业经验】0.3 为训练场景常见下限','NVIDIA'),
(85,'DCGM_FI_PROF_PIPE_TENSOR_ACTIVE (1004)','GPU',1,'DCGM_FI_PROF_PIPE_TENSOR_ACTIVE',2,2,'Tensor Core 流水线活跃周期占比（相对峰值可持续周期）','compute算力性能','比例(0~1)','0.3~0.8（混合精度训练）',1,0.8,0.3,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'★算力健康度基线，跨卡同负载横向对比，偏离中位数 10% 即标记慢卡','【行业经验】混合精度训练典型区间 0.3~0.8','NVIDIA'),
(86,'DCGM_FI_PROF_DRAM_ACTIVE (1005)','GPU',1,'DCGM_FI_PROF_DRAM_ACTIVE',2,4,'显存接口收发数据的活跃周期占比','compute算力性能','比例(0~1)','0.2~0.9',1,0.9,0.2,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'>0.9 且 SM_ACTIVE <0.3 → memory-bound，属性能问题','【行业经验】0.9 为访存瓶颈判定线','NVIDIA'),
(87,'DCGM_FI_PROF_PIPE_FP16_ACTIVE (1008)','GPU',1,'DCGM_FI_PROF_PIPE_FP16_ACTIVE',2,4,'FP16 流水线活跃周期占比（不含 HMMA）','compute算力性能','比例(0~1)','0~1.0',1,1,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'【官方规格】DCGM Field IDs','NVIDIA'),
(88,'DCGM_FI_DEV_TOTAL_APP_CLOCKS_VIOLATION (246)','GPU',1,'DCGM_FI_DEV_TOTAL_APP_CLOCKS_VIOLATION',4,1,'未能维持应用设定时钟的累计时长','compute算力性能','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'增量 >0 = 无法维持应用时钟（降频的旁证）','【官方规格】DCGM Field IDs','NVIDIA'),
(89,'DCGM_FI_DEV_TOTAL_BASE_CLOCKS_VIOLATION (247)','GPU',1,'DCGM_FI_DEV_TOTAL_BASE_CLOCKS_VIOLATION',4,1,'未能维持基准时钟的累计时长','compute算力性能','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'★增量 >0 = 已跌破基准频率，属严重降频，按高危扣分','【官方规格】DCGM Field IDs','NVIDIA'),
(90,'DCGM_FI_DEV_LOW_UTIL_VIOLATION (244)','GPU',1,'DCGM_FI_DEV_LOW_UTIL_VIOLATION',4,4,'因低利用率而限制时钟的累计时长','compute算力性能','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'GPU_UTIL >10% 时应为 0 μs/s，空闲期增量属正常。属节能行为，非故障，健康度评分中不扣分','【官方规格】DCGM Field IDs','NVIDIA'),
(91,'DCGM_FI_DEV_SYNC_BOOST_VIOLATION (242)','GPU',1,'DCGM_FI_DEV_SYNC_BOOST_VIOLATION',4,2,'Sync Boost 组内被其他卡拖低时钟的累计时长','compute算力性能','μs','0',NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,0,'增量 >0 表示同组存在慢卡，需定位组内最热或最受限的那张','【官方规格】DCGM Field IDs','NVIDIA'),
(92,'DCGM_FI_DEV_DEC_UTIL（206）','GPU',1,'DCGM_FI_DEV_DEC_UTIL',2,4,'视频解码器(NVENC)利用率','compute算力性能','%','0～100',100,100,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'训练场景通常恒为 0；持续偏高多为编解码型业务，非硬件故障','【官方规格】DCGM Field IDs','NVIDIA'),
(93,'DCGM_FI_DEV_ENC_UTIL（205）','GPU',1,'DCGM_FI_DEV_ENC_UTIL',2,4,'视频编码器(NVENC)利用率','compute算力性能','%','0～100',100,100,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'训练场景通常恒为 0；持续偏高多为编解码型业务，非硬件故障','【官方规格】DCGM Field IDs','NVIDIA'),
(94,'DCGM_FI_DEV_VGPU_LICENSE_STATUS','GPU',4,'DCGM_FI_DEV_VGPU_LICENSE_STATUS',6,3,'vGPU 授权(许可)状态；仅在启用 vGPU/GRID 授权时有效','driver驱动（DCGM）',NULL,'恒为 1（已授权）',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,0,'1 = 已获得有效授权(Licensed)；0 = 未授权/授权失效(Unlicensed)','【官方规格】DCGM Field IDs','NVIDIA'),
(95,'DCGM_FI_DEV_BAR1_FREE','GPU',1,'DCGM_FI_DEV_BAR1_FREE',1,4,'BAR1 空闲显存（PCIe BAR1 可寻址显存剩余量）','memory显存可靠性','MB','0~max',0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'与 BAR1_TOTAL/USED 配套；BAR1_FREE = BAR1_TOTAL - BAR1_USED','DCGM Field IDs：BAR1 相关字段〔1〕','NVIDIA'),
(96,'DCGM_FI_PROF_PIPE_FP64_ACTIVE','GPU',1,'DCGM_FI_PROF_PIPE_FP64_ACTIVE',1,4,'FP64 运算管线活跃占比','compute算力性能','%','0~100',NULL,100,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'双精度算力活跃度；训练类任务通常接近 0，科学计算类才显著','DCGM Profiling 字段','NVIDIA'),
(97,'DCGM_FI_PROF_PIPE_FP32_ACTIVE','GPU',1,'DCGM_FI_PROF_PIPE_FP32_ACTIVE',1,4,'FP32 运算管线活跃占比','compute算力性能','%','0~100',NULL,100,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'FP32 算力活跃度，与 SM_ACTIVE、PIPE_TENSOR 联动看','DCGM Profiling','NVIDIA'),
(98,'DCGM_EXP_XID_ERRORS_COUNT','GPU',1,'DCGM_EXP_XID_ERRORS_COUNT',3,1,'XID 错误事件累计计数（Exporter 扩展）','stability运行稳定','次','0',NULL,0,0,0,0,1,'次/分钟',NULL,NULL,NULL,1,'出现即告警，须结合 XID code 定位；同 DCGM_FI_DEV_XID_ERRORS 但为 Exporter 汇总计数','DCGM Exporter EXP 指标','NVIDIA'),
(99,'DCGM_EXP_GPU_HEALTH_STATUS','GPU',1,'DCGM_EXP_GPU_HEALTH_STATUS',7,2,'DCGM 健康检查给出的 GPU 整体健康状态','stability运行稳定','枚举','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0 = HEALTHY；10 = WARNING；20 = FAILURE',1,'0=Healthy；1=Warning；2=Unhealthy（DCGM Health 状态），作旁路结论对照，部分是0，10，20','DCGM Health Status','NVIDIA'),
(100,'DCGM_FI_DEV_ECC_DBE_AGG_DEV','GPU',1,'DCGM_FI_DEV_ECC_DBE_AGG_DEV',3,1,'显存设备级双比特错误（DBE）聚合计数','memory显存可靠性','次','0',NULL,NULL,0,NULL,0,1,'次/分钟',NULL,NULL,NULL,1,'DBE 出现即为严重错误，须关注；与 _AGG_TOTAL 补充设备级明细','DCGM Field IDs','NVIDIA'),
(101,'DCGM_FI_DEV_ECC_DBE_AGG_SRM','GPU',1,'DCGM_FI_DEV_ECC_DBE_AGG_SRM',3,1,'SRAM（片上缓存）双比特错误累计计数','memory显存可靠性','次','0',NULL,NULL,0,NULL,0,1,'次/分钟',NULL,NULL,NULL,1,'SRAM DBE 属强故障证据，非零需评估 RMA','dcgm_errors.h','NVIDIA'),
(102,'DCGM_FI_DEV_ECC_DBE_VOL_SRM','GPU',1,'DCGM_FI_DEV_ECC_DBE_VOL_SRM',3,1,'SRAM 易失性双比特错误（DBE）累计','memory显存可靠性','次','0',NULL,NULL,0,NULL,0,1,'次/分钟',NULL,NULL,NULL,1,'易失性 DBE，可结合 VOL_TOTAL 与 AGG 对照','dcgm_errors.h','NVIDIA'),
(103,'DCGM_FI_DEV_HWR_COUNTER','GPU',1,'DCGM_FI_DEV_HWR_COUNTER',3,1,'硬件恢复（HWR）事件计数','stability运行稳定','次','0',NULL,NULL,0,NULL,0,1,'次/分钟',NULL,NULL,NULL,0,'硬件恢复/重试次数持续增长，说明链路或板级不稳定','DCGM Field IDs','NVIDIA'),
(104,'DCGM_FI_DEV_VOLTAGE','GPU',1,'DCGM_FI_DEV_VOLTAGE',1,2,'核心电压（当前工作电压）','stability运行稳定','mV','650 ~ 1100',1200,1100,650,500,NULL,NULL,NULL,NULL,NULL,NULL,0,'电压异常偏高/偏低需结合电源模块评估；正常范围随 SKU 型号不同','DCGM Field IDs','NVIDIA'),
(105,'DCGM_FI_DEV_VIDEO_CLOCK','GPU',1,'DCGM_FI_DEV_VIDEO_CLOCK',1,4,'视频引擎（编码/解码）时钟频率','compute算力性能','MHz','0~max',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'视频编解码任务性能参考；结合 ENC_UTIL/DEC_UTIL 看','DCGM Field IDs','NVIDIA'),
(106,'dcmi_get_device_temperature / 
npu-smi info -t temp/（npu-smi: Temperature(C) / Temp(C)）','NPU',1,'npu_chip_info_temperature',1,1,'昇腾 AI 处理器 die 当前温度','thermal温度散热','℃','20~85',95,85,20,0,NULL,NULL,NULL,NULL,NULL,NULL,1,'降频阈值 = 85（持续 >85℃ 触发频率限制）；软件保护停机线建议取 95','【实测值】空闲 37~48，满载约 60，>85 降频；【行业经验】华为未公开硬件关机温度，95 为运维侧主动停机建议值','华为昇腾'),
(107,'dcmi_get_device_hbm_info / npu-smi info -t memory/（npu-smi: HBM Temperature）','NPU',1,'npu_chip_info_hbm_temperature',1,1,'HBM 显存颗粒温度（区别于芯片整体温度）','thermal温度散热','℃','20~85',95,85,20,0,NULL,NULL,NULL,NULL,NULL,NULL,1,'降频阈值 = 85，HBM 过温同样触发整卡频率限制','【实测值】空闲约 38；【行业经验】HBM2e 颗粒结温上限 95，取 85 作保守告警线','华为昇腾'),
(108,'dcmi_get_device_power_info / npu-smi info -t power/（npu-smi: NPU Real-time Power(W) / Power(W)）','NPU',1,'npu_chip_info_power',1,2,'昇腾 AI 处理器实时功耗（部分形态为整板功耗）','power功耗电源','W','90~400',400,400,90,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'★功耗达到 400 触发功率封顶降频。Atlas 300T Pro PCIe 卡对应值为 300','【官方规格】昇腾 910 处理器 310W，910B OAM 模组 400W，Atlas 300T Pro 整卡最大 300W；【实测值】910B3 空闲 90~93，FP16 满载 231，训练峰值 273','华为昇腾'),
(109,'dcmi_get_device_voltage / npu-smi info -t volt/（npu-smi: Voltage(V)）','NPU',1,'npu_chip_info_voltage',1,2,'芯片核心供电电压','power功耗电源','V','0.76~0.84',NULL,0.84,0.76,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'电压跌出 ±5% 区间常与硬件供电保护降频同时出现','【行业经验】昇腾未公开标称核心电压，按 7nm AI 芯片通行值 0.8V ±5% 取定','华为昇腾'),
(110,'dcmi_get_device_utilization_rate (input_type=2) / npu-smi info -t usages/（npu-smi: Aicore Usage Rate(%) / AICore(%)）','NPU',1,'npu_chip_info_utilization',2,1,'AI Core 利用率','compute算力性能','%','60~99（训练稳定期）',100,99,60,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'vNPU 算力切分场景下该值可能恒为 0，此时无意义，需改用容器内指标','【实测值】训练稳定期 60~99；【官方规格】华为云 CCE NPU 指标说明','华为昇腾'),
(111,'dcmi_get_device_utilization_rate / npu-smi info -t usages/（npu-smi: Aivector Usage Rate(%)）','NPU',1,'npu_chip_info_vector_utilization',2,4,'Vector(矢量)计算单元利用率','compute算力性能','%','0~100',100,100,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与 AI Core 利用率差值应 <30 个百分点
与 AI Core 利用率长期背离 >30 个百分点提示算子调度异常','【实测值】通常与 AI Core 同步变化；【行业经验】30 个百分点为背离判据','华为昇腾'),
(112,'dcmi_get_device_frequency (input_type=7) / npu-smi info -t common/（npu-smi: Aicore curFreq(MHZ)）','NPU',1,'npu_chip_info_aicore_current_freq',1,1,'AI Core 当前实际频率，判断是否降频的直接观测量','compute算力性能','MHz','1710~1800（满载时）',NULL,1800,1710,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'★降频判据：满载时 curFreq < 1710（即 95% × 1800）→ 判定降频；再结合温度 >85 归因热降频、功耗触及 400 归因功率降频','【实测值】910B3 空闲 800，满载 1800；【行业经验】95% 为降频判定线','华为昇腾'),
(113,'dcmi_get_device_frequency (input_type=9) / npu-smi info -t common/（npu-smi: Aicore Freq(MHZ)）','NPU',1,'npu_chip_info_aicore_freq',1,2,'AI Core 标称(额定)频率','compute算力性能','MHz','1800~1800',1800,1800,1800,1800,NULL,NULL,NULL,NULL,NULL,NULL,0,'作为 curFreq 的分母基准','【实测值】910B3 = 1800 MHz','华为昇腾'),
(114,'dcmi_get_device_hbm_info / npu-smi info -t usages/（npu-smi: HBM Capacity(MB)）','NPU',1,'npu_chip_info_hbm_total_memory',1,1,'HBM 总容量','memory显存可靠性','MB','65536~65536',65536,65536,65536,65536,NULL,NULL,NULL,NULL,NULL,NULL,0,'关闭 ECC 后容量会升至约 95623 MB，属配置变更非故障。32GB 版基线为 32768','【实测值】910B 64GB 版 = 65536 MB','华为昇腾'),
(115,'dcmi_get_device_hbm_info / npu-smi info/（npu-smi: HBM-Usage(MB)）','NPU',1,'npu_chip_info_hbm_used_memory',1,4,'HBM 已用量','memory显存可靠性','MB','3300~62259',65536,62259,3300,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'空闲态 3300~3400 MB 为驱动保留（约 5%）；62259 = 总量 95%，为耗尽告警线','【实测值】910B3 空闲保留 3379 MB；【行业经验】95% 为告警水位','华为昇腾'),
(116,'dcmi_get_device_hbm_info / npu-smi info -t usages','NPU',1,'npu_chip_info_hbm_utilization',2,4,'HBM 使用率','memory显存可靠性','%','4~90',100,90,4,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'空闲约 4~5%；90% 为告警线','【实测值】空闲 4~5%；【行业经验】90% 告警','华为昇腾'),
(117,'dcmi_get_device_hbm_info / npu-smi info -t usages/（npu-smi: HBM Bandwidth Usage Rate(%)）','NPU',1,'npu_chip_info_hbm_bandwidth_utilization',2,4,'HBM 带宽利用率','memory显存可靠性','%','0~90',100,90,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'>90 且 AI Core 利用率 <30 = 访存瓶颈，属性能问题非硬件故障','【行业经验】90% 为访存瓶颈判定线','华为昇腾'),
(118,'dcmi_get_device_frequency (input_type=6) / npu-smi info -t memory/（npu-smi: HBM Clock Speed）','NPU',1,'npu_chip_info_hbm_freq',1,2,'HBM 工作频率','memory显存可靠性','MHz','1520~1600',NULL,1600,1520,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'1520 = 95% × 1600，为显存降频判定线','【实测值】910B = 1600 MHz，对应约 1.54 TB/s 带宽','华为昇腾'),
(119,'dcmi_get_device_ecc_info / npu-smi info -t ecc','NPU',1,'npu_chip_info_hbm_ecc_single_bit_error_cnt',3,1,'HBM 可纠正单比特 ECC 错误累计数','memory显存可靠性','次','0~1000',NULL,1000,0,NULL,0,24,'次/天',NULL,NULL,NULL,0,'≤1 次/小时；>24 次/天 判定 HBM 退化；>1000 次/天 判定需停机检修
累计 >1000 次建议安排 RMA 评估','【实测值】健康服务器该计数恒为 0；【行业经验】1000 次/天为业内通行检修线','华为昇腾'),
(120,'dcmi_get_device_ecc_info / npu-smi info -t ecc','NPU',1,'npu_chip_info_hbm_ecc_double_bit_error_cnt',3,1,'HBM 不可纠正双比特 ECC 错误累计数','memory显存可靠性','次','0~0',NULL,0,0,NULL,0,0,'次/天',NULL,NULL,NULL,1,'次/天，>0（任意一次即需立即隔离并硬件检查）','【实测值】健康服务器恒为 0；【行业经验】任意 >0 即 RMA 候选','华为昇腾'),
(121,'npu_chip_info_hbm_ecc_total_single_bit_error_cnt','NPU',1,'npu_chip_info_hbm_ecc_total_single_bit_error_cnt',3,1,'HBM生命周期单比特(可纠正)ECC累计','memory显存可靠性','次','0~1000',NULL,1000,0,NULL,0,24,'次/天',NULL,NULL,NULL,0,'可纠正;正常0次/天,>24次/天判HBM退化,累计>1000评估RMA','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(122,'npu_chip_info_hbm_ecc_total_double_bit_error_cnt','NPU',1,'npu_chip_info_hbm_ecc_total_double_bit_error_cnt',3,1,'HBM生命周期多比特(不可纠正)ECC累计','memory显存可靠性','次','0~0',NULL,0,0,NULL,0,0,'次/天',NULL,NULL,NULL,1,'不可纠正=数据损坏;正常0次/天,任何非零(告警速率0)即隔离并RMA','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(123,'dcmi_get_device_ecc_info / npu-smi info -t ecc','NPU',1,'npu_chip_info_hbm_ecc_single_bit_isolated_pages_cnt',3,1,'因单比特错误而被驱动隔离的 HBM 坏页数','memory显存可靠性','页','0',NULL,64,0,NULL,0,8,'页',NULL,NULL,NULL,0,'页/天；累计 >8 页进入关注，>64 页建议 RMA。持续增长（HBM 物理退化）','【实测值】健康服务器恒为 0；【行业经验】对齐 NVIDIA 页黑名单 64 页容量取定','华为昇腾'),
(124,'dcmi_get_device_ecc_info / npu-smi info -t ecc','NPU',1,'npu_chip_info_hbm_ecc_double_bit_isolated_pages_cnt',3,1,'因双比特错误而被驱动隔离的 HBM 坏页数','memory显存可靠性','页','0',NULL,64,0,NULL,0,8,'页',NULL,NULL,NULL,0,'页/天；累计 >8 页进入关注，>64 页建议 RMA。持续增长（HBM 物理退化）','【实测值】健康服务器恒为 0；【行业经验】对齐 NVIDIA 页黑名单 64 页容量取定','华为昇腾'),
(125,'npu-smi info -t ecc-enable / npu-smi set -t ecc-enable','NPU',4,'npu_chip_info_hbm_ecc_enable_flag',6,3,'HBM ECC 使能状态。关闭可释放约 30 GB 显存但完全失去纠错能力','memory显存可靠性',NULL,'恒为 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,0,'1 = Enabled；0 = Disabled（生产训练环境禁止）','【官方规格】npu-smi set -t ecc-enable -d 0/1','华为昇腾'),
(126,'dcmi_get_device_memory_info / npu-smi info/（npu-smi: Memory-Usage(MB)）','NPU',1,'npu_chip_info_used_memory',1,4,'DDR 内存已使用量。Atlas A2 训练系列无 DDR 模块，恒为 0','memory显存可靠性','MB','0~0（A2 训练系列）',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'带 DDR 的形态（如 Atlas 300T Pro，16 GB DDR4）上界改为 16384，告警线 15564（95%）','【官方规格】MindCluster 文档：Atlas A2 训练系列产品没有 DDR 模块，不上报相关指标','华为昇腾'),
(127,'dcmi_get_device_memory_info/（npu-smi: DDR Capacity(MB)）','NPU',1,'npu_chip_info_total_memory',1,4,'DDR 内存总量','memory显存可靠性','MB','0~0（A2 训练系列）',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'Atlas 300T Pro 形态为 16384 MB','【官方规格】华为云 CCE NPU 指标说明','华为昇腾'),
(128,'npu-smi info -t hccs-bw -i <id> -c 0 -time 100','NPU',2,'npu_chip_info_hccs_bandwidth_info_total_tx',1,2,'HCCS 链路实测带宽（发送）','interconnect昇腾互连通信','GB/s','23.6~112',NULL,112,23.6,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'112 GB/s 为物理上限（全双工）；应用层 P2P 实测约 26.2 GB/s，23.6 = 26.2 的 90%，为 P2P 劣化判定线','【实测值】910B3 P2P 实测 26.2 GB/s（ascend-dmi）；【行业经验】90% 为衰减判定线','华为昇腾'),
(129,'npu-smi info -t hccs-bw -i <id> -c 0 -time 100','NPU',2,'npu_chip_info_hccs_bandwidth_info_total_rx',1,2,'HCCS 链路实测带宽（接收）','interconnect昇腾互连通信','GB/s','23.6~112',NULL,112,23.6,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'112 GB/s 为物理上限（全双工）；应用层 P2P 实测约 26.2 GB/s，23.6 = 26.2 的 90%，为 P2P 劣化判定线','【实测值】910B3 P2P 实测 26.2 GB/s（ascend-dmi）；【行业经验】90% 为衰减判定线','华为昇腾'),
(130,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_1',1,4,'第1条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(131,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_2',1,4,'第2条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(132,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_3',1,4,'第3条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(133,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_4',1,4,'第4条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(134,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_5',1,4,'第5条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(135,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_6',1,4,'第6条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(136,'npu_chip_info_hccs_bandwidth_info_tx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_tx_7',1,4,'第7条HCCS链路单链路发送带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B单HCCS链路约56GB/s(半双工);应用层P2P约26GB/s;显著偏低提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(137,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_1',1,4,'第1条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(138,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_2',1,4,'第2条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(139,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_3',1,4,'第3条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(140,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_4',1,4,'第4条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(141,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_5',1,4,'第5条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(142,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_6',1,4,'第6条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(143,'npu_chip_info_hccs_bandwidth_info_rx_X','NPU',2,'npu_chip_info_hccs_bandwidth_info_rx_7',1,4,'第7条HCCS链路单链路接收带宽','interconnect昇腾互连通信','GB/s','50~56',NULL,56,50,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'与tx对照;总HCCS双向392GB/s;反映卡间AllReduce能力','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(144,'dcmi_get_device_network_health / hccn_tool -i <id> -link -g','NPU',5,'npu_chip_info_network_status',7,1,'卡上 200GE RoCE 网口的链路状态','interconnect昇腾互连通信',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 = UP / Success；0 = DOWN（跨机集合通信直接中断）',0,NULL,'【官方规格】DCMI dcmi_get_device_network_health；华为云 CCE NPU 指标说明','华为昇腾'),
(145,'hccn_tool -i <id> -bandwidth -g','NPU',5,'npu_chip_info_bandwidth_tx',8,4,'RoCE 网口实时发送速率（瞬时速率）','interconnect昇腾互连通信','MB/s','0~25000',25000,25000,12500,0,12500,0,NULL,NULL,NULL,NULL,0,'25000 MB/s = 200GE 线速；长期低于 12500 需排查拥塞或链路降级','【官方规格】昇腾 910B 集成 1×200GE RoCE；【行业经验】50% 线速为跨机训练下限','华为昇腾'),
(146,'hccn_tool -i <id> -bandwidth -g','NPU',5,'npu_chip_info_bandwidth_rx',8,4,'RoCE 网口实时接收速率（瞬时速率）','interconnect昇腾互连通信','MB/s','0~25000',25000,25000,12500,0,12500,0,NULL,NULL,NULL,NULL,0,'25000 MB/s = 200GE 线速；长期低于 12500 需排查拥塞或链路降级','【官方规格】昇腾 910B 集成 1×200GE RoCE；【行业经验】50% 线速为跨机训练下限','华为昇腾'),
(147,'hccn_tool -i <id> -stat -g','NPU',5,'npu_chip_roce_rx_err_pkt_num',3,1,'RoCE接收坏包(错包)数','interconnect昇腾互连通信','次','0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'错包与乱序 0 次/小时；CNP >100 次/秒 判定网络拥塞；错包/乱序 >0；CNP 持续增长（拥塞，表现为集合通信超时）','【行业经验】RoCE 无损网络下错包应为 0；CNP 100 次/秒为拥塞告警线','华为昇腾'),
(148,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_temp',1,2,'光模块工作温度','interconnect昇腾互连通信','℃','0~70',NULL,70,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'超过 70℃ 误码率显著上升并引发链路重训','【行业经验】商用温度等级光模块工作上限 70℃','华为昇腾'),
(149,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_tx_power_0',1,2,'光模块通道0发送光功率','interconnect昇腾互连通信','dBm','-7~2',NULL,2,-7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(150,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_tx_power_1',1,2,'光模块通道1发送光功率','interconnect昇腾互连通信','dBm','-7~2',NULL,2,-7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(151,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_tx_power_2',1,2,'光模块通道2发送光功率','interconnect昇腾互连通信','dBm','-7~2',NULL,2,-7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(152,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_tx_power_3',1,2,'光模块通道3发送光功率','interconnect昇腾互连通信','dBm','-7~2',NULL,2,-7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(153,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_rx_power_0',1,2,'光模块通道0接收光功率','interconnect昇腾互连通信','dBm','-10~0.5',NULL,0.5,-10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(154,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_rx_power_1',1,2,'光模块通道1接收光功率','interconnect昇腾互连通信','dBm','-10~0.5',NULL,0.5,-10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(155,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_rx_power_2',1,2,'光模块通道2接收光功率','interconnect昇腾互连通信','dBm','-10~0.5',NULL,0.5,-10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(156,'hccn_tool -i <id> -optical -g','NPU',5,'npu_chip_optical_rx_power_3',1,2,'光模块通道3接收光功率','interconnect昇腾互连通信','dBm','-10~0.5',NULL,0.5,-10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'接收光功率低于 -10 dBm 判定光链路衰减超标','【行业经验】200G 光模块通行工作区间','华为昇腾'),
(157,'dcmi_get_device_health / npu-smi info -t health/（npu-smi: Health）','NPU',1,'npu_chip_info_health_status',7,1,'昇腾 AI 处理器综合健康状态，健康度评估的一级判据','reliability昇腾可靠性与运行状态',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 = OK（npu-exporter 中 1 表示健康）；0 = 不健康。npu-smi 细分：Warning（一般告警，温度/功耗接近阈值或 ECC 增长）；Alarm（重要告警）；Critical（紧急，需立即停任务）；UNKNOWN（设备不存在或未启动）',1,'Alarm / Critical 常由持续高温、电源异常或严重硬件错误触发','【官方规格】华为云 CCE NPU 指标说明（0=不健康，1=健康）','华为昇腾'),
(158,'npu-exporter','NPU',1,'npu_chip_info_error_code',7,1,'npu-exporter 上报的芯片错误码（故障码）','reliability昇腾可靠性与运行状态',NULL,'0~0',NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,'0；≠ 0',0,NULL,'【官方规格】MindCluster NPU Exporter Prometheus Metrics 接口','华为昇腾'),
(159,'ascend-dmi --bw','NPU',1,'npu_chip_info_process_info',1,2,'HBM 实测读写带宽','auxiliary辅助与效率指标','GB/s','1386~1540',NULL,1540,1386,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'1540 GB/s（1.54 TB/s）为 910B 标称值；低于 1386（90%）判定显存性能衰减','【实测值】910B HBM 约 1.54 TB/s；【行业经验】90% 为验收下限','华为昇腾'),
(160,'ascend-dmi --bw','NPU',1,'npu_chip_info_process_info_num',1,2,'占用处理器的进程数量','auxiliary辅助与效率指标','个',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,'华为昇腾'),
(161,'npu_chip_roce_new_pkt_rty_num','NPU',5,'npu_chip_roce_new_pkt_rty_num',3,2,'RoCE新报文重传(retry)数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,10,'次/秒',NULL,NULL,NULL,0,'少量重传可接受;持续增长(>10次/秒)提示链路丢包或拥塞,导致RDMA传输效率下降与集合通信长尾','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(162,'npu_chip_roce_out_of_order_num','NPU',5,'npu_chip_roce_out_of_order_num',3,2,'RoCE乱序报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,10,'次/秒',NULL,NULL,NULL,0,'偶发乱序不影响业务(有重排);持续增长提示多路径/网络抖动,可能触发重传影响性能','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(163,'npu_chip_roce_rx_cnp_pkt_num','NPU',5,'npu_chip_roce_rx_cnp_pkt_num',3,2,'RoCE接收CNP(拥塞通知)数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,100,'次/秒',NULL,NULL,NULL,0,'接收到对端CNP表示本端发送速率过快致对端拥塞,本端将降速;持续高值提示网络路径拥塞','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(164,'npu_chip_info_overall_utilization','NPU',1,'npu_chip_info_overall_utilization',2,4,'处理器整体利用率(综合AI Core/Vector)','compute算力性能','%','60~99',100,99,60,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'训练稳定期应60~99%;长期<10%提示任务空转;=0且非空闲需排查调度','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(165,'container_npu_utilization','NPU',1,'container_npu_utilization',2,4,'带容器信息的AI Core利用率(容器维度)','compute算力性能','%','0~100',100,100,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'vNPU/容器切分场景替代整卡利用率;训练期应处高水位','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(166,'container_npu_total_memory','NPU',1,'container_npu_total_memory',1,4,'带容器信息的NPU总内存(容器维度)','memory显存可靠性','MB','按容器规格(如16384/32768/65536)',NULL,65536,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'静态配置量,作容器内存使用率分母;非0恒定','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(167,'container_npu_used_memory','NPU',1,'container_npu_used_memory',1,4,'带容器信息的NPU已用内存(容器维度)','memory显存可靠性','MB','0~total',NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'接近total×95%时容器内OOM风险高','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(168,'npu_chip_info_link_status','NPU',5,'npu_chip_info_link_status',7,1,'网口(RoCE)Link状态(Atlas训练系列)','interconnect昇腾互连通信',NULL,'恒为1/UP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1=UP链路正常;0=DOWN链路断(跨机训练必失败)',1,'DOWN即集合通信中断,立即排查光模块/线缆/交换机端口','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(169,'npu_chip_link_speed','NPU',5,'npu_chip_link_speed',1,2,'网口默认(协商)速率','interconnect昇腾互连通信','Mb/s','200000~200000(200GE)',200000,200000,200000,190000,NULL,NULL,NULL,NULL,NULL,NULL,0,'910B网口额定200GE=200000Mb/s;实测Speed:200000Mb/s;低于额定提示降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(170,'npu_chip_link_up_num','NPU',5,'npu_chip_link_up_num',3,2,'网口UP状态统计次数(累计翻转)','interconnect昇腾互连通信','次','0~N',NULL,NULL,0,NULL,0,1,'次/小时',NULL,NULL,NULL,0,'短时间频繁增长提示链路抖动(up/down翻转),排查物理链路','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(171,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_1',3,2,'第1条HCCS链路发送报文数(采集失败-1)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(172,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_2',3,2,'第1条HCCS链路发送报文数(采集失败-2)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(173,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_3',3,2,'第1条HCCS链路发送报文数(采集失败-3)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(174,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_4',3,2,'第1条HCCS链路发送报文数(采集失败-4)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(175,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_5',3,2,'第1条HCCS链路发送报文数(采集失败-5)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(176,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_6',3,2,'第1条HCCS链路发送报文数(采集失败-6)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(177,'npu_chip_info_hccs_statistic_info_tx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_tx_cnt_7',3,2,'第1条HCCS链路发送报文数(采集失败-7)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=该链路采集失败',0,'正常持续增长;长期不增长提示无流量或异常;-1需排查采集','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(178,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_1',3,2,'第1条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(179,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_2',3,2,'第2条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(180,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_3',3,2,'第3条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(181,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_4',3,2,'第4条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(182,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_5',3,2,'第5条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(183,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_6',3,2,'第6条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(184,'npu_chip_info_hccs_statistic_info_rx_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_rx_cnt_7',3,2,'第7条HCCS链路接收报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'-1=采集失败',0,'与tx_cnt对照;收发严重不对称提示单向链路问题','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(185,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_1',3,1,'第1条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(186,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_2',3,1,'第2条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(187,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_3',3,1,'第3条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(188,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_4',3,1,'第4条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(189,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_5',3,1,'第5条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(190,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_6',3,1,'第6条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(191,'npu_chip_info_hccs_statistic_info_crc_err_cnt_X','NPU',2,'npu_chip_info_hccs_statistic_info_crc_err_cnt_7',3,1,'第7条HCCS链路CRC错误报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,'-1=采集失败',0,'CRC应恒0;正常0次/小时,>0提示HCCS物理链路误码,持续增长影响卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(192,'npu_chip_info_hccs_bandwidth_info_profiling_time','NPU',2,'npu_chip_info_hccs_bandwidth_info_profiling_time',1,2,'HCCS带宽采样时长(配置项1~1000)','interconnect昇腾互连通信','s','1~1000',NULL,1000,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'采样窗口配置参数,非故障指标,用于解释带宽统计口径','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(193,'npu_chip_info_pcie_rx_p_bw','NPU',2,'npu_chip_info_pcie_rx_p_bw',1,4,'PCIe接收远端写(Posted)带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(194,'npu_chip_info_pcie_rx_np_bw','NPU',2,'npu_chip_info_pcie_rx_np_bw',1,4,'PCIe接收远端读(Non-Posted)带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(195,'npu_chip_info_pcie_rx_cpl_bw','NPU',2,'npu_chip_info_pcie_rx_cpl_bw',1,4,'PCIe远端读收到CPL回复带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(196,'npu_chip_info_pcie_tx_p_bw','NPU',2,'npu_chip_info_pcie_tx_p_bw',1,4,'PCIe向远端写(Posted)带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(197,'npu_chip_info_pcie_tx_np_bw','NPU',2,'npu_chip_info_pcie_tx_np_bw',1,4,'PCIe向远端读(Non-Posted)带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(198,'npu_chip_info_pcie_tx_cpl_bw','NPU',2,'npu_chip_info_pcie_tx_cpl_bw',1,4,'PCIe回复远端读CPL带宽','interconnect昇腾互连通信','MB/s','24000~31500(Gen4x16单向)',NULL,31500,24000,0,NULL,NULL,NULL,NULL,NULL,NULL,0,'PCIe4.0x16单向理论≈31500MB/s(31.5GB/s);长期<24000且非空闲提示PCIe降速','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(199,'npu_chip_mac_rx_pause_num','NPU',5,'npu_chip_mac_rx_pause_num',3,2,'MAC接收PAUSE帧总数(链路级流控)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,10,'次/秒',NULL,NULL,NULL,0,'流控帧正常低频;持续增长提示下游拥塞或流控频繁触发','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(200,'npu_chip_mac_tx_pause_num','NPU',5,'npu_chip_mac_tx_pause_num',3,2,'MAC发送PAUSE帧总数(链路级流控)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,10,'次/秒',NULL,NULL,NULL,0,'本端主动发PAUSE;持续增长提示本端拥塞','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(201,'npu_chip_mac_rx_pfc_pkt_num','NPU',5,'npu_chip_mac_rx_pfc_pkt_num',3,2,'MAC接收PFC(优先级流控)帧总数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,100,'次/秒',NULL,NULL,NULL,0,'RoCE无损网络依赖PFC;激增提示网络拥塞','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(202,'npu_chip_mac_tx_pfc_pkt_num','NPU',5,'npu_chip_mac_tx_pfc_pkt_num',3,2,'MAC发送PFC帧总数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,100,'次/秒',NULL,NULL,NULL,0,'本端发PFC背压;持续激增提示本端接收拥塞','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(203,'npu_chip_mac_rx_bad_pkt_num','NPU',5,'npu_chip_mac_rx_bad_pkt_num',3,2,'MAC接收坏包数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(204,'npu_chip_mac_tx_bad_pkt_num','NPU',5,'npu_chip_mac_tx_bad_pkt_num',3,2,'MAC发送坏包数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(205,'npu_chip_mac_rx_bad_oct_num','NPU',5,'npu_chip_mac_rx_bad_oct_num',3,2,'MAC接收坏包字节数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(206,'npu_chip_mac_tx_bad_oct_num','NPU',5,'npu_chip_mac_tx_bad_oct_num',3,2,'MAC发送坏包字节数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(207,'npu_chip_roce_rx_all_pkt_num','NPU',5,'npu_chip_roce_rx_all_pkt_num',3,2,'RoCE接收总报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,NULL,'次/秒',NULL,NULL,NULL,0,'流量基线,作坏包率/CNP比率分母;持续增长正常','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(208,'npu_chip_roce_tx_all_pkt_num','NPU',5,'npu_chip_roce_tx_all_pkt_num',3,2,'RoCE发送总报文数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,NULL,'次/秒',NULL,NULL,NULL,0,'流量基线,作发送侧错误率分母;持续增长正常','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(209,'npu_chip_roce_tx_err_pkt_num','NPU',5,'npu_chip_roce_tx_err_pkt_num',3,2,'RoCE发送坏包数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,>0提示发送侧报文错误','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(210,'npu_chip_roce_tx_cnp_pkt_num','NPU',5,'npu_chip_roce_tx_cnp_pkt_num',3,2,'RoCE发送CNP(拥塞通知)数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,100,'次/秒',NULL,NULL,NULL,0,'本端发CNP通知对端降速;持续高值提示本端接收侧拥塞','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(211,'npu_chip_roce_unexpected_ack_num','NPU',5,'npu_chip_roce_unexpected_ack_num',3,2,'非预期ACK数(丢弃,不影响业务)','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,NULL,'次/小时',NULL,NULL,NULL,0,'一般不影响业务;仅辅助诊断,激增可结合乱序综合判断','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(212,'npu_chip_roce_verification_err_num','NPU',5,'npu_chip_roce_verification_err_num',3,2,'域段校验失败报文数(icrc/长度/端口)','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,>0提示报文校验失败(链路误码或配置错误)','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(213,'npu_chip_roce_qp_status_err_num','NPU',5,'npu_chip_roce_qp_status_err_num',3,2,'QP连接状态异常报文数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,>0提示QP连接异常(集合通信中断/超时)','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(214,'npu_chip_info_rx_ecn_num','NPU',5,'npu_chip_info_rx_ecn_num',3,2,'网络接收ECN标记数','interconnect昇腾互连通信','个','0~N',NULL,NULL,0,NULL,0,100,'次/秒',NULL,NULL,NULL,0,'ECN反映网络拥塞;持续高值提示拥塞,排查交换机/组网','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(215,'npu_chip_info_rx_fcs_num','NPU',5,'npu_chip_info_rx_fcs_num',3,2,'网络接收FCS(帧校验)错误数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,FCS错误提示物理层误码(线缆/光模块)','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(216,'npu_chip_info_sio_crc_tx_err_cnt','NPU',2,'npu_chip_info_sio_crc_tx_err_cnt',3,2,'SIO(超节点串行IO)发送CRC错包数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,>0提示SIO链路误码,影响超节点内卡间通信','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(217,'npu_chip_info_sio_crc_rx_err_cnt','NPU',2,'npu_chip_info_sio_crc_rx_err_cnt',3,2,'SIO接收CRC错包数','interconnect昇腾互连通信','个','0~0',NULL,0,0,NULL,0,0,'次/小时',NULL,NULL,NULL,0,'应恒0;正常0次/小时,>0提示SIO链路误码','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(218,'npu_chip_optical_state','NPU',4,'npu_chip_optical_state',7,1,'光模块在位状态','interconnect昇腾互连通信',NULL,'恒为在位',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1=在位present;0=不在位或异常',0,'不在位将导致对应网口Link Down,跨机训练失败','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾'),
(219,'npu_chip_optical_vcc','NPU',4,'npu_chip_optical_vcc',1,2,'光模块工作电压(VCC)','interconnect昇腾互连通信','V','3.13~3.47(3.3V±5%)',3.47,3.3,3.3,3.13,NULL,NULL,NULL,NULL,NULL,NULL,0,'额定3.3V;正常3.13~3.47V,超出±5%提示供电异常(误码/掉线)','【华为云CCE NPU指标cce_10_0970】+【MindCluster NPU-Exporter】+【昇腾910B实测:ArthurChiao鲲鹏8*910B华为云环境/知乎910B带宽实测】','华为昇腾');

SELECT COUNT(*) AS total FROM accel_metric_scoring;
SELECT vendor, COUNT(*) AS cnt FROM accel_metric_scoring GROUP BY vendor;
SELECT owner_subject_code, COUNT(*) AS cnt FROM accel_metric_scoring GROUP BY owner_subject_code;
SELECT value_type_code, COUNT(*) AS cnt FROM accel_metric_scoring GROUP BY value_type_code;
SELECT health_purpose_code, COUNT(*) AS cnt FROM accel_metric_scoring GROUP BY health_purpose_code;
SELECT is_veto, COUNT(*) AS cnt FROM accel_metric_scoring GROUP BY is_veto;
SELECT COUNT(*) AS has_rate_unit FROM accel_metric_scoring WHERE rate_unit IS NOT NULL;
